# Generated by Django 5.1.1 on 2024-10-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_budgetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pma_admin',
            field=models.BooleanField(default=False),
        ),
    ]
