# Generated by Django 5.1.1 on 2024-10-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_is_pma_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_pma_admin',
        ),
    ]
