# Generated by Django 5.1.1 on 2024-11-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20241027_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
