# Generated by Django 5.1.1 on 2024-11-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_file_description_file_keywords'),
        ('core', '0016_merge_20241027_0020'),
    ]

    operations = [
    ]
