# Generated by Django 5.1.1 on 2024-11-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_organization_category_organization_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.CharField(choices=[('small', 'Small (1-10)'), ('medium', 'Medium (11-50)'), ('large', 'Large (51+)')], default='small', max_length=20),
        ),
    ]
