# Generated by Django 5.1.1 on 2024-11-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_message_announcement_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
    ]
