# Generated by Django 5.1.1 on 2024-11-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_announcement_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
