# Generated by Django 5.1.1 on 2024-11-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20241111_1455'),
        ('core', '0020_alter_organization_size'),
        ('core', '0022_announcement_is_visible'),
    ]

    operations = [
    ]
