# Generated by Django 5.1.1 on 2024-11-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_announcement_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
