# Generated by Django 5.1.1 on 2024-11-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20241114_1505'),
        ('core', '0023_merge_20241114_1508'),
    ]

    operations = [
    ]
