# Generated by Django 5.1.1 on 2024-11-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20241111_1455'),
        ('core', '0020_alter_organization_size'),
        ('core', '0025_file_title'),
    ]

    operations = [
    ]
