# Generated by Django 5.1.1 on 2024-11-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20241117_1547'),
        ('core', '0027_sync_file_state'),
    ]

    operations = [
    ]
