# Generated by Django <version> on <date>

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_file_title'),
        ('core', '0025_file_title'),
        ('core', '0027_sync_file_state'),
    ]

    operations = []
