# Generated by Django 5.1.1 on 2024-10-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_slug_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.project'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='core.project'),
        ),
    ]
