# Generated by Django 5.1.1 on 2024-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organization_feed_visible_alter_file_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_picture',
            field=models.ImageField(blank=True, null=True, upload_to='organization_pics/'),
        ),
    ]
