# Generated by Django 5.1.1 on 2024-10-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_budgetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, help_text='Description of file contents'),
        ),
        migrations.AddField(
            model_name='file',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
    ]
