# Generated by Django 5.1.1 on 2024-10-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_organization_picture'),
        ('core', '0015_remove_userprofile_is_pma_admin'),
    ]

    operations = [
    ]
