# Generated by Django 5.1.1 on 2024-11-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20241108_2322'),
        ('core', '0018_merge_20241108_2336'),
    ]

    operations = [
    ]
