# Generated by Django 5.1.1 on 2024-11-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='message',
            new_name='content',
        ),
    ]
